name: nc-aio-optimizations

services:
  nc-aio-optimizations:
    image: docker:27-cli
    container_name: nc-aio-optimizations
    restart: "no"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /mnt/apps/dockge/master-nextcloud-aio:/stack:ro
      - /mnt/apps/dockge/nc-aio-optimizations:/out
    working_dir: /stack
    command: ["sh", "/stack/scripts/optimizations/host-apply-optimizations.sh"]
    environment:
      OUT_DIR: /out
      STACK_DIR: /stack
